"""add full_name to users

Revision ID: 87bcdb79c07d
Revises: 6ea23294a3df
Create Date: 2026-02-11 18:38:58.266189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87bcdb79c07d'
down_revision: Union[str, None] = '6ea23294a3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_id'), 'waitlist', ['id'], unique=False)
    op.add_column('book_history', sa.Column('status_to', sa.Enum('AVAILABLE', 'RESERVED', 'BORROWED', 'OVERDUE', name='bookstatus'), nullable=False))
    op.add_column('book_history', sa.Column('photo_proof_path', sa.String(), nullable=True))
    op.add_column('book_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_book_history_id'), 'book_history', ['id'], unique=False)
    op.drop_column('book_history', 'status')
    op.drop_column('book_history', 'timestamp')
    op.add_column('books', sa.Column('isbn', sa.String(length=20), nullable=True))
    op.add_column('books', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('books', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'BORROWED', name='bookstatus'),
               nullable=True)
    op.alter_column('books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_books_author', table_name='books')
    op.drop_index('ix_books_genre', table_name='books')
    op.drop_index('ix_books_status', table_name='books')
    op.drop_index('ix_books_title', table_name='books')
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'username')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.create_index('ix_books_title', 'books', ['title'], unique=False)
    op.create_index('ix_books_status', 'books', ['status'], unique=False)
    op.create_index('ix_books_genre', 'books', ['genre'], unique=False)
    op.create_index('ix_books_author', 'books', ['author'], unique=False)
    op.alter_column('books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('books', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'BORROWED', name='bookstatus'),
               nullable=False)
    op.alter_column('books', 'genre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('books', 'is_deleted')
    op.drop_column('books', 'isbn')
    op.add_column('book_history', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('book_history', sa.Column('status', postgresql.ENUM('AVAILABLE', 'RESERVED', 'BORROWED', name='bookstatus'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_book_history_id'), table_name='book_history')
    op.drop_column('book_history', 'created_at')
    op.drop_column('book_history', 'photo_proof_path')
    op.drop_column('book_history', 'status_to')
    op.drop_index(op.f('ix_waitlist_id'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
