FROM python:3.11-slim

WORKDIR /app

# Копируем requirements и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY . .

# Expose порт для webhook
EXPOSE 8001

# Запуск бота
CMD ["python", "main.py"]
